name: CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  mod-tests:
    name: Mod Tests (Lua 5.2, Linux)
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v5

    - name: Install Lua 5.2
      run: |
        sudo apt-get update
        sudo apt-get install -y lua5.2 liblua5.2-dev luarocks

    - name: Install dev dependencies
      run: |
        sudo luarocks install --only-deps factorio-mocks-generator-dev-1.rockspec

    - name: Run mod tests with coverage
      run: busted --output=TAP --run=mod

    - name: Generate coverage report
      run: luacov

    - name: Display coverage report
      run: cat luacov.report.out

    - name: Upload coverage results
      uses: actions/upload-artifact@v4
      with:
        name: mod-coverage-report
        path: |
          luacov.report.out
